apiVersion: autoscaling.x-k8s.io/v1alpha1
kind: StartupCPUBoost
metadata:
  name: boost-001
  namespace: {{ .Values.namespace }}
selector:
  matchExpressions:
  - key: app.kubernetes.io/name
    operator: In
    values: ["{{ .Values.labels.app }}"]
spec:
  resourcePolicy:
    containerPolicies:
    - containerName: {{ .Values.container.name }}
      percentageIncrease:
        value: 50
  durationPolicy:
    # fixedDuration:
    #   unit: Seconds
    #   value: 60
    podCondition:
      type: Ready
      status: "True"