apiVersion: autoscaling.x-k8s.io/v1alpha1
kind: StartupCPUBoost
metadata:
  name: {{ .Release.Name }}-startup-cpu-boost
  namespace: {{ .Values.namespace }}
selector:
  matchLabels:
    app: {{ .Values.labels.app }}
spec:
  resourcePolicy:
    containerPolicies:
    - containerName: {{ .Values.container.name }}
      percentageIncrease:
        value: 50
  durationPolicy:
    fixedDuration:
      unit: Seconds
      value: 300
    # podCondition:
    #   type: Ready
    #   status: "True"