# Default values for your-application.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
namespace: hello-world

container:
  name: hello-world-app

image:
  repository: ctr20/rest-service
  tag: latest
  pullPolicy: Always

service:
  type: NodePort
  port: 8080
  targetPort: 8080

spring:
  profiles:
    active: production

resources:
  limits:
    cpu: "500m"
    memory: "256Mi"
  requests:
    cpu: "250m"
    memory: "512Mi"

labels:
  app: hello-world-app
  tier: backend
  environment: production
  deployment: hello-world-app
  service: hello-world-service
